#!/bin/sh

# run Verilator to translate Verilog into C++_, including C++ testbench
verilator -Wall --cc --trace top.sv counter.sv bin2bcd.sv --exe top_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtop.mk Vtop

# run execuitable simulation file
obj_dir/Vtop
